-- 1. THE USERS: Stores the identity and their "Golden Baseline"
CREATE TABLE UserProfiles (
    profile_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing ID
    user_hash VARCHAR2(64) NOT NULL,                                -- Anonymous ID (Privacy first!)
    device_type VARCHAR2(20),                                       -- 'mobile' or 'desktop'
    avg_dwell NUMBER(10,4) DEFAULT 0.0,                             -- Avg time key is held down
    avg_flight NUMBER(10,4) DEFAULT 0.0,                            -- Avg time between keys
    session_count NUMBER DEFAULT 0,                                 -- How many logins have we seen?
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP                -- Last time profile was updated
);

-- 2. THE SESSIONS: Stores every single login attempt to track drift
CREATE TABLE BehaviorLogs (
    log_id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,                  -- Globally unique ID generated by Oracle
    profile_id NUMBER,                                              -- Links back to UserProfiles
    captured_score NUMBER(10,4),                                    -- How well did they match today?
    is_anomaly NUMBER(1) DEFAULT 0,                                 -- 1 if behavior was a mismatch (Oracle uses NUMBER for booleans)
    is_bot NUMBER(1) DEFAULT 0,                                     -- 1 if variance was too low (perfect timing)
    raw_jitter NUMBER(10,4),                                        -- Store the variance score for debugging
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                  -- Record creation time
);

-- 3. THE RAW DATA (Optional): For deep analysis later
CREATE TABLE RawEvents (
    event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Auto-incrementing ID
    log_id RAW(16),                                                 -- Links back to BehaviorLogs
    event_type VARCHAR2(10),                                        -- 'KEY' or 'MOUSE'
    delta_ms NUMBER                                                 -- The actual timing in milliseconds
);
