-- 1. THE USERS: Stores the identity and their "Golden Baseline"
CREATE TABLE UserProfiles (
    profile_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Unique ID for each user profile
    user_hash VARCHAR2(64) NOT NULL,                                -- Salted hash of UserID for privacy
    device_type VARCHAR2(20),                                       -- Context: 'mobile' or 'desktop'
    avg_dwell NUMBER(10,4) DEFAULT 0.0,                             -- Baseline: Avg time key is held down
    avg_flight NUMBER(10,4) DEFAULT 0.0,                            -- Baseline: Avg time between keys
    session_count NUMBER DEFAULT 0,                                 -- Count of successful logins for drift calc
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP                -- Last time the 'Golden Baseline' changed
);

-- SEED DATA: Add a dummy user so you can test your code immediately
INSERT INTO UserProfiles (user_hash, device_type, avg_dwell, avg_flight, session_count)
VALUES ('test_user_123', 'desktop', 85.0, 120.0, 3); -- Starting at 3 sessions for testing

COMMIT;

-- 2. THE SESSIONS: Audit and mismatch tracking
CREATE TABLE BehaviorLogs (
    log_id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,                  -- Unique ID for this specific session
    profile_id NUMBER,                                              -- Links back to the User Profile
    prev_log_id RAW(16),                                            -- Links to the previous session (The Trail)
    captured_score NUMBER(10,4),                                    -- The Euclidean distance calculated today
    is_anomaly NUMBER(1) DEFAULT 0,                                 -- 1 if behavior was a human mismatch
    is_test_mode NUMBER(1) DEFAULT 1                                -- 1 if the mode is testing
    is_bot NUMBER(1) DEFAULT 0,                                     -- 1 if variance was too low (Bot detected)
    raw_jitter NUMBER(10,4),                                        -- Standard deviation of timings
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                  -- Exact time of login attempt
);



-- 3. THE RAW DATA (Optional): For deep analysis later
CREATE TABLE RawEvents (
    event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Auto-incrementing ID
    log_id RAW(16),                                                 -- Links back to BehaviorLogs
    event_type VARCHAR2(10),                                        -- 'KEY' or 'MOUSE'
    delta_ms NUMBER                                                 -- The actual timing in milliseconds
);

-- 4. THE ARCHIVE: For cold storage
CREATE TABLE BehaviorLogs_Archive AS SELECT * FROM BehaviorLogs WHERE 1=0;
